Repository zingolabs/zaino, pull requests merged in 2025-03, with the labels that each got.

#226 update docs
  README.md
  docs/Zaino-zcash-rpcs.pdf
  docs/internal_architecture.pdf
  docs/internal_spec.md
  docs/lib_system_architecture.pdf
  docs/live_system_architecture.pdf
  docs/rpc_api.md
  docs/testing.md
  docs/use_cases.md
  docs/zaino_lib_system_architecture.pdf
  docs/zaino_live_system_architecture.pdf
  docs/zaino_serve_architecture_v020.pdf
  docs/zaino_state_architecture_v020.pdf
Labels: ZGM2, tracking

#228 Add state service tests
  zaino-fetch/src/jsonrpc/response.rs
  zaino-state/src/fetch.rs
  zaino-state/src/local_cache/finalised_state.rs
  zaino-state/src/local_cache/non_finalised_state.rs
  zaino-state/src/state.rs
Labels: ZGM2

#234 update state tests to testnet
  integration-tests/tests/state_service.rs
  zaino-testutils/src/lib.rs
Labels: PriorityHigh, ZGM2

#240 CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation
