Repository zingolabs/zaino, pull requests merged in 2025-04, with the labels that each got.

#260 improved ci
  .config/nextest.toml
  .github/workflows/ci.yml
Labels: test

#259 use_rustls_instead_of_openSSL_for_reqwest
  Cargo.toml
Labels: Zallet

#258 reverse get_latest_block block hash
  integration-tests/tests/fetch_service.rs
  integration-tests/tests/wallet_to_validator.rs
  zaino-state/src/fetch.rs
Labels: Zallet

#264 State service subscriber
  integration-tests/tests/local_cache.rs
  integration-tests/tests/state_service.rs
  zaino-state/src/config.rs
  zaino-state/src/error.rs
  zaino-state/src/fetch.rs
  zaino-state/src/indexer.rs
  zaino-state/src/local_cache.rs
  zaino-state/src/local_cache/finalised_state.rs
  zaino-state/src/local_cache/non_finalised_state.rs
  zaino-state/src/state.rs
  zaino-state/src/utils.rs
  zainod/src/indexer.rs
Labels: ZGM3

#244 Lightwalletindexer and zcashindexer for stateservice
  Cargo.lock
  integration-tests/tests/state_service.rs
  zaino-state/Cargo.toml
  zaino-state/src/fetch.rs
  zaino-state/src/indexer.rs
  zaino-state/src/local_cache.rs
  zaino-state/src/state.rs
  zaino-state/src/utils.rs
  zainod/src/error.rs
  zainod/src/indexer.rs
Labels: ZGM3
